# Generated by Django 6.0 on 2025-12-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mục Menu')),
                ('url_slug', models.CharField(max_length=200, unique=True, verbose_name='Đường dẫn (URL Slug)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Thứ tự hiển thị')),
                ('is_published', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Mục Menu',
                'verbose_name_plural': 'Các Mục Menu',
                'ordering': ['order'],
            },
        ),
    ]
