# Generated by Django 6.0 on 2025-12-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên Tag')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug Tag')),
            ],
            options={
                'verbose_name': 'Thẻ (Tag)',
                'verbose_name_plural': 'Các Thẻ (Tags)',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Mục Menu/Danh mục', 'verbose_name_plural': 'Các Mục Menu/Danh mục'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên mục Menu/Danh mục'),
        ),
    ]
