# Generated by Django 6.0 on 2025-12-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khach_hang', models.IntegerField(default=0)),
                ('san_pham_da_ban', models.IntegerField(default=0)),
                ('don_hang', models.IntegerField(default=0)),
                ('doanh_thu', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('revenue', models.FloatField()),
            ],
        ),
    ]
