
"""
Django settings for web_django project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""






from pathlib import Path








# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f3)14(%h0sn7=(^m9s^vwjb)_tq8!p&#0$fihjrr2736ik6u7k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.ngrok-free.app',
]


# ================================
# APPLICATION DEFINITION
# ================================
# INSTALLED_APPS:
# Danh sách TẤT CẢ các ứng dụng (apps) mà Django sẽ:
#  - Nạp khi khởi động project
#  - Tạo bảng CSDL khi migrate
#  - Cho phép sử dụng model, admin, template, static, signals,...
# Thứ tự trong danh sách này RẤT QUAN TRỌNG đối với một số app

INSTALLED_APPS = [

    # =====================================================
    # 1. JAZZMIN – GIAO DIỆN ADMIN NÂNG CAO
    # =====================================================
    # Jazzmin là package giúp:
    #  - Thay đổi toàn bộ giao diện Django Admin mặc định
    #  - Giao diện hiện đại, đẹp, dễ dùng
    #  - Hỗ trợ sidebar, icon, dark mode, dashboard
    #
    # ⚠️ BẮT BUỘC PHẢI ĐẶT TRÊN CÙNG
    # Nếu đặt sau 'django.contrib.admin' → giao diện KHÔNG ÁP DỤNG
    'jazzmin',


    # =====================================================
    # 2. UNFOLD – ADMIN UI KHÁC (HIỆN ĐANG KHÔNG DÙNG)
    # =====================================================
    # unfold là một thư viện admin UI khác tương tự Jazzmin
    # Chỉ dùng MỘT trong hai: jazzmin HOẶC unfold
    # Đang comment để tránh xung đột
    # 'unfold',


    # =====================================================
    # 3. DJANGO CORE APPS – ỨNG DỤNG LÕI CỦA DJANGO
    # =====================================================

    # Admin site:
    # - Giao diện quản trị (/admin)
    # - Quản lý user, group, model
    'django.contrib.admin',

    # Authentication:
    # - Quản lý đăng nhập / đăng xuất
    # - User, Group, Permission
    # - Phân quyền hệ thống
    'django.contrib.auth',

    # Content Types:
    # - Django dùng để liên kết model động
    # - Phục vụ hệ thống permission, generic relations
    'django.contrib.contenttypes',

    # Sessions:
    # - Lưu phiên đăng nhập
    # - Lưu dữ liệu tạm theo user
    'django.contrib.sessions',

    # Messages:
    # - Hiển thị thông báo dạng:
    #   + Thành công
    #   + Lỗi
    #   + Cảnh báo
    # - Ví dụ: "Lưu thành công", "Xóa thất bại"
    'django.contrib.messages',

    # Static Files:
    # - Quản lý file tĩnh: CSS, JS, ảnh
    # - BẮT BUỘC cho giao diện website & admin
    'django.contrib.staticfiles',


    # =====================================================
    # 4. APP TỰ TẠO – ỨNG DỤNG CHÍNH CỦA WEBSITE
    # =====================================================
    # app:
    # - Chứa toàn bộ logic website:
    #   + Models (MenuItem, Post, Banner, ...)
    #   + Views
    #   + Templates
    #   + Static riêng của app
    #   + Admin customize
    #
    # ⚠️ BẮT BUỘC phải đăng ký tại đây
    # nếu không:
    #   - migrate KHÔNG tạo bảng
    #   - admin KHÔNG hiển thị model
    'app',


    # =====================================================
    # 5. CKEDITOR – TRÌNH SOẠN THẢO NỘI DUNG
    # =====================================================

    # ckeditor:
    # - Cho phép dùng trình soạn thảo WYSIWYG
    # - Hỗ trợ:
    #   + In đậm, nghiêng, gạch chân
    #   + Chèn link, bảng
    #   + HTML nâng cao
    'ckeditor',

    # ckeditor_uploader:
    # - Mở rộng cho ckeditor
    # - Cho phép upload ảnh, file trực tiếp khi soạn bài
    # - Dùng cho các field như:
    #   RichTextUploadingField
    #
    # ⚠️ BẮT BUỘC phải cài CẢ 2:
    #   ckeditor + ckeditor_uploader
    'ckeditor_uploader',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


WSGI_APPLICATION = 'web_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_web',   # tên database trong phpMyAdmin
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        # 'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}








# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = [
    BASE_DIR / 'app/static',
]

MEDIA_ROOT = BASE_DIR / 'app/static'
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'
CKEDITOR_UPLOAD_PATH = "uploads/"


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        #  KHÔNG tự ghi width / height
        'image_resize': False,
        #  KHÔNG cho chỉnh size trong Image Properties
        'removePlugins': 'image,resize',
        #  Style ảnh mặc định
        'contentsCss': [
            '/static/css/ckeditor_custom.css',
        ],
    }
}
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




